routes/admin.php
<?php
/**
 * Admin Router
 */
$router->group([
    'prefix'     => 'admin/',
    'as'         => 'admin.',
    'namespace'  => 'Backend\Admin\\',
    'middleware' => [ 'auth', 'auth.admin', 'authorize' ]
] , function () use ( $router) {

    //user route

    $router->get('user/quick-details/{id}', [
        'as'   => 'user.quickdetails',
        'uses' => 'UserController@getUserQuickDetails'
    ]);

    $router->get('user/create/{role}', [
        'as'   => 'user.create',
        'uses' => 'UserController@create'
    ]);

    $router->post('user/store/{role}', [
        'as'   => 'user.store',
        'uses' => 'UserController@store'
    ]);

    $router->get('user/{role}', [
        'as'   => 'user.index',
        'uses' => 'UserController@index'
    ]);

    $router->get('user/{user}/message', [
        'as'   => 'user.msg',
        'uses' => 'UserController@getMessage'
    ]);

    $router->post('user/{user}/message/send', [
        'as'   => 'user.msg.send',
        'uses' => 'UserController@sendMessage'
    ]);

    $router->get('user/{user}/view/overview', [
        'as'   => 'user.view.overview',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/view/setting', [
        'as'   => 'user.view.setting',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/view/setting/edit', [
        'as'   => 'user.view.setting.edit',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/view/slot', [
        'as'   => 'user.view.slot',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/view/slot/{id}', [
        'as'   => 'user.view.slot.detail',
        'uses' => 'UserController@slotDetail'
    ]);

    $router->get('user/{user}/view/slot/project/{slug}', [
        'as'   => 'user.view.slot.project',
        'uses' => 'UserController@projectDetail'
    ]);

    $router->get('user/{user}/view/social-media', [
        'as'   => 'user.view.socialmedia',
        'uses' => 'UserController@socialMediaDetail'
    ]);

    $router->get('user/{user}/view/review', [
        'as'   => 'user.view.review',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/view/review/{id}/edit', [
        'as'   => 'user.view.review.edit',
        'uses' => 'UserController@reviewEdit'
    ]);

    $router->post('user/{user}/view/review/{id}/delete', [
        'as'   => 'user.view.review.delete',
        'uses' => 'UserController@reviewDelete'
    ]);

    $router->post('user/{user}/view/review/{id}/update', [
        'as'   => 'user.view.review.update',
        'uses' => 'UserController@reviewUpdate'
    ]);

    $router->get('user/{user}/view/help', [
        'as'   => 'user.view.help',
        'uses' => 'UserController@view'
    ]);

    $router->get('user/{user}/edit', [
        'as'   => 'user.edit',
        'uses' => 'UserController@edit'
    ]);

    $router->post('user/{user}/update', [
        'as'   => 'user.update',
        'uses' => 'UserController@update'
    ]);

    $router->post('updateAvatar', [
        'as'   => 'user.updateAvatar',
        'uses' => 'UserController@updateAvatar'
    ]);

    $router->post('user/{user}/delete', [
        'as'   => 'user.delete',
        'uses' => 'UserController@delete'
    ]);

    $router->post('user/{user}/ban', [
        'as'   => 'user.ban',
        'uses' => 'UserController@banUser'
    ]);

    $router->get('reset/password', [
        'as'   => 'user.reset.password',
        'uses' => 'PasswordResetController@index'
    ]);

    $router->post('reset/password', [
        'as'   => 'user.reset.password',
        'uses' => 'PasswordResetController@reset'
    ]);

    $router->get('slots/getSlotReview', [
        'as' => 'user.getSlotReview',
        'uses' => 'UserController@getSlotReview'
    ]);

    //category controller routes
    $router->get('category', [
        'as'    => 'category.index',
        'uses'  => 'CategoryController@index'
    ]);

    $router->get('category/create', [
        'as'    => 'category.create',
        'uses'  => 'CategoryController@create'
    ]);

    $router->post('category/store', [
        'as'    => 'category.store',
        'uses'  => 'CategoryController@store'
    ]);

    $router->get('category/{id}/edit', [
        'as'    => 'category.edit',
        'uses'  => 'CategoryController@edit'
    ]);

    $router->post('category/{id}/update', [
        'as'    => 'category.update',
        'uses'  => 'CategoryController@update'
    ]);

    $router->post('category/{id}/delete', [
        'as'    => 'category.delete',
        'uses'  => 'CategoryController@destroy'
    ]);

    //category subcategory level2

    $router->get('category/level2/{cat_id}/{type}', [
        'as'    => 'category.level2.index',
        'uses'  => 'CategoryController@index'
    ]);

    $router->get('category/level2/{cat_id}/{type}/create', [
        'as'    => 'category.level2.create',
        'uses'  => 'CategoryController@create'
    ]);

    $router->get('category/level2/{id}/{cat_id}/{type}/edit', [
        'as'    => 'category.level2.edit',
        'uses'  => 'CategoryController@edit'
    ]);

    //category subcategory level3

    $router->get('category/level3/{cat_id}/{type}', [
        'as'    => 'category.level3.index',
        'uses'  => 'CategoryController@index'
    ]);

    $router->get('category/level3/{cat_id}/{type}/create', [
        'as'    => 'category.level3.create',
        'uses'  => 'CategoryController@create'
    ]);

    $router->get('category/level3/{id}/{cat_id}/{type}/edit', [
        'as'    => 'category.level3.edit',
        'uses'  => 'CategoryController@edit'
    ]);

    //category subcategory level4

    $router->get('category/level4/{cat_id}/{type}', [
        'as'    => 'category.level4.index',
        'uses'  => 'CategoryController@index'
    ]);

    $router->get('category/level4/{cat_id}/{type}/create', [
        'as'    => 'category.level4.create',
        'uses'  => 'CategoryController@create'
    ]);

    $router->get('category/level4/{id}/{cat_id}/{type}/edit', [
        'as'    => 'category.level4.edit',
        'uses'  => 'CategoryController@edit'
    ]);

    //Social Media
    $router->get('social-media', [
        'as'    => 'socialmedia.index',
        'uses'  => 'SocialMediaController@index'
    ]);

    $router->get('social-media/create', [
        'as'    => 'socialmedia.create',
        'uses'  => 'SocialMediaController@create'
    ]);

    $router->post('social-media/store', [
        'as'    => 'socialmedia.store',
        'uses'  => 'SocialMediaController@store'
    ]);

    $router->post('social-media/{id}/delete', [
        'as'    => 'socialmedia.delete',
        'uses'  => 'SocialMediaController@delete'
    ]);

    //Social Media Attributes
    $router->get('social-media/attributes', [
        'as'    => 'socialmedia.attributes.index',
        'uses'  => 'SocialMediaController@indexAttributes'
    ]);

    $router->get('social-media/attributes/create', [
        'as'    => 'socialmedia.attributes.create',
        'uses'  => 'SocialMediaController@createAttribute'
    ]);

    $router->post('social-media/attributes/store', [
        'as'    => 'socialmedia.attributes.store',
        'uses'  => 'SocialMediaController@storeAttribute'
    ]);

    $router->post('social-media/attributes/{id}/delete', [
        'as'    => 'socialmedia.attributes.delete',
        'uses'  => 'SocialMediaController@deleteAttribute'
    ]);

    //RoleController routes
    $router->get('roles',                     [ 'as' => 'roles.index',    'uses' => 'Acl\RolesController@index']);
    $router->get('roles/create',              [ 'as' => 'roles.create',   'uses' => 'Acl\RolesController@create']);
    $router->post('roles/store',              [ 'as' => 'roles.store',    'uses' => 'Acl\RolesController@store']);
    $router->get('roles/show/{roleId}',       [ 'as' => 'roles.show',     'uses' => 'Acl\RolesController@show']);
    $router->get('roles/{roleId}/edit',       [ 'as' => 'roles.edit',     'uses' => 'Acl\RolesController@edit']);
    $router->post('roles/{roleId}/update',    [ 'as' => 'roles.update',   'uses' => 'Acl\RolesController@update']);
    $router->post('roles/getInfo',            [ 'as' => 'roles.get-info', 'uses' => 'Acl\RolesController@getInfo']);
    $router->get('roles/{roleId}/confirm-delete', [
        'as'   => 'roles.confirm-delete',
        'uses' => 'Acl\RolesController@getModalDelete'
    ]);
    $router->post('roles/{roleId}/delete', [
        'as'   => 'roles.delete',
        'uses' => 'Acl\RolesController@destroy'
    ]);

    //PermissionController routes
    $router->get('permissions',        [
        'as'   => 'permissions.index',
        'uses' => 'Acl\PermissionsController@index'
    ]);
    $router->get('permissions/create', [
        'as'   => 'permissions.create',
        'uses' => 'Acl\PermissionsController@create'
    ]);
    $router->post('permissions/store', [
        'as'   => 'permissions.store',
        'uses' => 'Acl\PermissionsController@store'
    ]);
    $router->get('permissions/show/{permissionId}', [
        'as' => 'permissions.show',
        'uses' => 'Acl\PermissionsController@show'
    ]);
    $router->get('permissions/{permissionId}/edit', [
        'as'   => 'permissions.edit',
        'uses' => 'Acl\PermissionsController@edit'
    ]);
    $router->post('permissions/{permissionId}/update', [
        'as'   => 'permissions.update',
        'uses' => 'Acl\PermissionsController@update'
    ]);
    $router->get('permissions/generate', [
        'as'   => 'permissions.generate',
        'uses' => 'Acl\PermissionsController@generate'
    ]);
    $router->post('routes/savePerms', [
        'as'   => 'routes.save-perms',
        'uses' => 'Acl\RoutesController@savePerms'
    ]);
    $router->get('routes/search', [
        'as'   => 'routes.search',
        'uses' => 'Acl\RoutesController@searchByName'
    ]);
    $router->post('routes/getInfo', [

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Authentication Routes...
$router->get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('geo');
$router->post('login', 'Auth\LoginController@login')->middleware('geo');
$router->post('logout', 'Auth\LoginController@logout')->name('logout');
$router->get('blocked', 'Auth\LoginController@blocked')->name('blocked');

$router->get('user/login/{service}', ['as' => 'social.login', 'uses' => 'Auth\LoginController@redirectToProvider']);
$router->get('user/login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

// Registration Routes...
$router->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register')->middleware('geo');
$router->post('register', 'Auth\RegisterController@register')->middleware('geo');

// Password Reset Routes...
$router->get('password/reset',         'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$router->post('password/reset',        'Auth\ResetPasswordController@reset')->name('password.reset');

$router->get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/error', 'HomeController@index')->name('error');


/*$router->get('customer/dashboard', function () {
    return view('backend.customer.dashboard.index');
})->middleware(['auth','auth.customer'])->name('customer.dashboard');*/


$router->get('admin/error/{code}', 'Backend\ErrorController@index')->name('admin.error');


$router->get('stripe/card', 'StripeController@payWithStripe')->name('addmoney.stripe');
$router->post('stripe/card', 'StripeController@stripe')->name('stripe');

Route::get('paywithpaypal', array('as' => 'addmoney.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
Route::post('paypal', array('as' => 'addmoney.paypal','uses' => 'AddMoneyController@postPaymentWithpaypal',));
Route::get('paypal', array('as' => 'payment.status','uses' => 'AddMoneyController@getPaymentStatus',));

Route::get('paypal/fund', array('as' => 'payment.fund.status',
    'uses' => 'Backend\Customer\FundController@getPaymentStatus',));


$router->get('markAsRead', function(){
	auth()->user()->unreadNotifications->markAsRead();
});

$router->get('verify', ['as' => 'verify', 'uses' => 'Auth\VerificationController@verify']);
$router->get('verify/{token}', ['as' => 'user.verification', 'uses' => 'Auth\VerificationController@verify']);

app/Http/Controllers/Backend/Admin/Acl/UsersRoleAction.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 9/6/2017
 * Time: 10:47 AM
 */

namespace App\Http\Controllers\Backend\Admin\Acl;

use App\Http\Controllers\AclBaseController;
use App\Evemoo\Models\Role;
use App\User;
use AppHelper;
use ConfigHelper;
use Illuminate\Http\Request;
use AclHelper;

class UsersRoleAction extends AclBaseController
{

    public $view_path      = 'admin.acl.users';
    protected $base_route  = 'admin.users';
    protected $folder_name = 'user';

    public function userRolesHtml($id)
    {
        if (!$user = User::find($id)) {
            AppHelper::unAuthorizedAccess();
        }
        $default_roles = Role::where('enabled', 1)->whereIn('name', ConfigHelper::getDefaultRoles())->get();
        return response()->json(json_encode([
            'message' => view($this->view_path.'.partials.roles', [
                'roles' => $user->roles,
                'default_roles' => $default_roles,
            ])->render(),

            'title' => 'Role(s) for <strong>'.join(' ', [$user->first_name, $user->middle_name, $user->last_name]).'</strong>'
        ]));
    }

    public function updateUserRoles(Request $request, $id)
    {
        $response = [
            'error' => true,
            'role_names_html' => ''
        ];

        if ($user = User::find($id)) {

            $response['error'] = false;
            $role_ids = [];
            foreach ($request->get('roles') as $item) {
                if ($role = AclHelper::getUserRoleModel($item)) {
                    $role_ids[] = $role->id;
                }
            }

            $user->roles()->sync($role_ids);
            foreach ($user->roles()->orderBy('name')->get() as $role) {
                $response['role_names_html'] .= '| <strong>'. $role->name.'</strong> | ';
            }

        }

        return response()->json(json_encode($response));
    }

}

resources/views/backend/admin/acl/roles/index.blade.php
@extends('backend.master.layout')

@section('style-css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
@endsection

@section('content')

    <div class="page-content">

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{ route('admin.dashboard') }}">{{ admin_trans($trans_path.'content.common.dashboard') }}</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="{{ route($base_route.'.index') }}">{{ admin_trans($trans_path.'content.common.roles') }}</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span>{{ admin_trans($trans_path.'content.list.list') }}</span>
                </li>
            </ul>
            <div class="page-toolbar"></div>
        </div>

        <br/>

        <div class="row">

            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title">

                        <div class="caption">
                            <i class="fa fa-list font-red"></i>
                            <span class="caption-subject font-red sbold uppercase">
                                {{ admin_trans($trans_path.'content.list.description') }}
                            </span>
                        </div>


                        <div class="actions">

                            <div class="btn-group btn-group-devided" data-toggle="buttons">

                                <a href="{{ route($base_route.'.create') }}"
                                   onclick="location.href = '{{ route($base_route.'.create') }}'">

                                    <button type="button"
                                            class="btn btn-primary mt-ladda-btn ladda-button btn-circle"
                                            data-style="expand-right">
                                        <span class="ladda-label">
                                            <i class="fa fa-plus-circle"></i>
                                            {{ admin_trans($trans_path.'button.add') }}
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </button>
                                </a>
                            </div>

                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="table-scrollable">

                            @include('backend.common.flash')

                            <table class="table table-hover table-light">
                                <thead class="flip-content">
                                <tr>
                                    <th>{{ admin_trans($trans_path . 'columns.name') }}</th>
                                    <th>{{ admin_trans($trans_path . 'columns.display_name') }}</th>
                                    <th>{{ admin_trans($trans_path . 'columns.description') }}</th>
                                    <th>{{ admin_trans($trans_path . 'columns.permissions') }}</th>
                                    <th>{{ admin_trans($trans_path . 'columns.users') }}</th>
                                    <th>{{ admin_trans($trans_path . 'columns.actions') }}</th>
                                </tr>
                                </thead>
                                <tbody>

                                @if($roles->count() > 0)


                                    @foreach($roles as $role)
                                        <tr>

                                            <td>{!! link_to_route('admin.roles.show', $role->name, [$role->id], []) !!}</td>
                                            <td>{!! link_to_route('admin.roles.show', $role->display_name, [$role->id], []) !!}</td>
                                            <td>{{ $role->description }}</td>
                                            <td>{{ $role->perms->count() }}</td>
                                            <td>{{ $role->users->count() }}</td>
                                            <td>
                                                @if ( $role->isEditable() )
                                                    <a href="{!! route('admin.roles.edit', $role->id) !!}"
                                                       title="{{ trans('general.button.edit') }}"><i
                                                                class="fa fa-pencil-square-o"></i></a>
                                                @else
                                                    <i class="fa fa-pencil-square-o text-muted"
                                                       title="{{ trans($trans_path . 'general.error.cant-edit-this-role') }}"></i>
                                                @endif

                                                @if ( $role->enabled )
                                                    <a
                                                       title="{{ trans('general.button.disable') }}"><i
                                                                class="fa fa-check-circle-o enabled"></i></a>
                                                @else
                                                    <a
                                                       title="{{ trans('general.button.enable') }}"><i
                                                                class="fa fa-ban disabled"></i></a>
                                                @endif

                                                @if ( $role->isDeletable() )
                                                    <a id="delete-item" href="javascript:void();"
                                                       data-id="{{$role->id}}"
                                                       title="{{ trans('general.button.delete') }}"><i
                                                                class="fa fa-trash-o deletable"></i></a>
                                                @else
                                                    <i class="fa fa-trash-o text-muted"
                                                       title="{{ trans($trans_path . 'general.error.cant-delete-this-role') }}"></i>
                                                @endif
                                            </td>

                                            {{-- <td>
                                                 <a href="{{ route($base_route.'.edit', $package->id) }}"
                                                    class="btn btn-outline btn-circle btn-sm blue">
                                                     <i class="fa fa-pencil"></i>
                                                     {{ admin_trans($trans_path.'content.list.edit') }}
                                                 </a>

                                                 <a data-href="{{ route($base_route.'.delete', $package->id) }}"
                                                    class="btn btn-outline btn-circle btn-sm red  delete-record-warning">
                                                     <i class="fa fa-trash"></i>
                                                     {{ admin_trans($trans_path.'content.list.delete') }}
                                                 </a>

                                             </td>--}}
                                        </tr>
                                    @endforeach

                                    <tr>
                                        <td colspan="6">{{ $roles->appends(request()->all())->render() }}</td>
                                    </tr>
                                @else
                                    <tr>
                                        <td colspan="6">{{ admin_trans($trans_path.'error.no-data-found') }}</td>
                                    </tr>
                                @endif

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->
            </div>
        </div>

    </div>



@endsection

@section('script-js')

    {{-- @include('admin.common.script')--}}
    {{-- @include('backend.admin.includes.delete')--}}


@endsection

resources/views/backend/admin/acl/roles/show.blade.php
@extends('layouts.master')

@section('head_extra')
    <!-- Select2 css -->
    @include('partials._head_extra_select2_css')

@endsection

@section('content')
    <section id="widget-grid" class="">
        <div class='row'>
            <div class='col-md-12'>
            <div class="box-body">

                {!! Form::model($role, ['route' => 'admin.roles.index', 'method' => 'GET']) !!}

                <!-- Custom Tabs -->
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab_details" data-toggle="tab" aria-expanded="true">{!! trans('general.tabs.details') !!}</a></li>
                        <li class=""><a href="#tab_options" data-toggle="tab" aria-expanded="false">{!! trans('general.tabs.options') !!}</a></li>
                        <li class=""><a href="#tab_perms" data-toggle="tab" aria-expanded="false">{!! trans('general.tabs.perms') !!}</a></li>
                        <li class=""><a href="#tab_users" data-toggle="tab" aria-expanded="false">{!! trans('general.tabs.users') !!}</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_details">
                            <div class="form-group">
                                {!! Form::label('name', trans($trans_path. 'general.columns.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'readonly']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('display_name', trans($trans_path. 'general.columns.display_name')) !!}
                                {!! Form::text('display_name', null, ['class' => 'form-control', 'readonly']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('description', trans($trans_path. 'general.columns.description')) !!}
                                {!! Form::text('description', null, ['class' => 'form-control', 'readonly']) !!}
                            </div>
                        </div><!-- /.tab-pane -->

                        <div class="tab-pane" id="tab_options">
                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        {!! Form::checkbox('resync_on_login', '1', $role->resync_on_login, ['disabled']) !!} {!! trans($trans_path. 'general.columns.resync_on_login') !!}
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        {!! Form::checkbox('enabled', '1', $role->enabled, ['disabled']) !!} {!! trans('general.status.enabled') !!}
                                    </label>
                                </div>
                            </div>
                        </div><!-- /.tab-pane -->

                        <div class="tab-pane" id="tab_perms">
                            <div class="form-group">
                                <div class="col-4">
                                    @foreach($perms as $perm)
                                        <div class="checkbox">
                                            <label>
                                                {!! Form::checkbox('perms[]', $perm->id, $role->hasPerm($perm), ['disabled']) !!} {{ $perm->display_name }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div><!-- /.tab-pane -->

                        <div class="tab-pane" id="tab_users">
                            <div class="form-group">
                                <div class="input-group select2-bootstrap-append">
                                    {!! Form::select('user_search', [], null, ['class' => 'form-control', 'id' => 'user_search', 'disabled' => 'disabled',  'style' => "width: 100%"]) !!}
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" disabled>
                                            <span class="fa fa-plus-square"></span>
                                        </button>
                                    </span>
                                </div>

                                <div class="box-body table-responsive no-padding">
                                    <table class="table table-hover">
                                        <tbody>
                                        <tr>
                                            <th>{!! trans(AppHelper::getTransPathFromViewPath('acl.users'). 'general.columns.name')  !!}</th>
                                            <th>{!! trans(AppHelper::getTransPathFromViewPath('acl.users'). 'general.columns.username')  !!}</th>
                                            <th>{!! trans(AppHelper::getTransPathFromViewPath('acl.users'). 'general.columns.enabled')  !!}</th>
                                            <th style="text-align: right">{!! trans(AppHelper::getTransPathFromViewPath('acl.users'). 'general.columns.actions')  !!}</th>
                                        </tr>
                                        @foreach($role->users as $user)
                                            <tr>
                                                <td>{!! link_to_route('admin.users.show', $user->full_name, [$user->id], []) !!}</td>
                                                <td>{!! link_to_route('admin.users.show', $user->username, [$user->id], []) !!}</td>
                                                <td>
                                                    @if($user->enabled)
                                                        <i class="fa fa-check text-green"></i>
                                                    @else
                                                        <i class="fa fa-close text-red"></i>
                                                    @endif
                                                </td>
                                                <td style="text-align: right">
                                                    <i class="fa fa-trash-o text-muted"></i>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div><!-- /.table-responsive -->
                            </div><!-- /.form-group -->
                        </div><!-- /.tab-pane -->

                    </div><!-- /.tab-content -->
                </div>

                <div class="form-group">
                    {!! Form::submit(trans('general.button.close'), ['class' => 'btn btn-primary']) !!}
                    @if ( $role->isEditable() || $role->canChangePermissions() )
                        <a href="{!! route('admin.roles.edit', $role->id) !!}" title="{{ trans('general.button.edit') }}" class='btn btn-default'>{{ trans('general.button.edit') }}</a>
                    @endif
                </div>

                {!! Form::close() !!}

            </div><!-- /.box-body -->
        </div><!-- /.col -->

    </div><!-- /.row -->
    </section>
@endsection

@section('body_bottom')
    <!-- Select2 js -->
    @include('partials._body_bottom_select2_js_user_search')
@endsection